---
- name: Install Python3 and PostgreSQL libraries
  become: yes
  apt:
    name:
      - python3
      - python3-pip
      - libpq-dev
    state: present

- name: Install psycopg2
  become: yes
  pip:
    name: psycopg2
    state: present

- name: Install PostgreSQL
  become: yes
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
