---
- name: Create database
  become: yes
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"

- name: Create user with password and all privileges
  become: yes
  community.postgresql.postgresql_user:
    db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    priv: "ALL"
    state: present
