---
- name: Install Nginx
  import_tasks: install.yml

- name: Configure Nginx
  import_tasks: configure.yml

- name: Enable Nginx service
  import_tasks: enable.yml

- name: Remove default Nginx site
  import_tasks: remove_default.yml

- name: Ensure Nginx is running
  import_tasks: ensure_running.yml

- name: Reload Nginx service
  import_tasks: reload.yml
