---
- name: Install required utilities
  apt:
    name:
      - tar
      - unzip
      - git
      - postgresql
      - postgresql-contrib
      - python3
      - python3-pip
    state: present
  become: yes
